FROM python:3.13-slim

WORKDIR /app

# Замена репозитория Debian на российское зеркало + установка пакетов
RUN sed -i 's/deb.debian.org/mirror.yandex.ru/g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn psycopg2-binary

COPY . .

CMD ["gunicorn", "waf_project.wsgi:application", "--bind", "0.0.0.0:8000"]