sonar.projectKey=<git account_name(SnegirYu naverno)>_<project name (WAF naverno)>
sonar.organization=<git account name(SnegirYu naverno)>

sonar.python.version=3.13
sonar.sources=.

sonar.exclusions=**/venv/**, **/.github/**, **/*.html